version = 0.1

[default.deploy.parameters]
stack_name = "supply-chain"
resolve_s3 = true
s3_prefix = "supply-chain"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "ProjectName=\"retail-supermarket\""
image_repositories = []

[default.global.parameters]
region = "us-west-2"
